# Generated by Django 3.0.6 on 2020-05-17 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('modified_date', models.DateField()),
                ('created_date', models.DateField()),
                ('id', models.DecimalField(decimal_places=10, editable=False, max_digits=19, primary_key=True, serialize=False)),
                ('forum_id', models.DecimalField(decimal_places=10, max_digits=19)),
                ('role_id', models.DecimalField(decimal_places=10, max_digits=19)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('modified_date', models.DateField()),
                ('created_date', models.DateField()),
                ('id', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='forum.Admin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('modified_date', models.DateField()),
                ('created_date', models.DateField()),
                ('id', models.DecimalField(decimal_places=10, editable=False, max_digits=19, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('subscribers', models.ManyToManyField(blank=True, to='account.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('modified_date', models.DateField()),
                ('created_date', models.DateField()),
                ('id', models.DecimalField(decimal_places=10, editable=False, max_digits=19, primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
