# Generated by Django 3.0.6 on 2020-05-18 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import spice.common.enum.vote_type


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('modified_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('id', models.DecimalField(decimal_places=10, editable=False, max_digits=19, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=250)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('modified_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('id', models.DecimalField(decimal_places=10, editable=False, max_digits=19, primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[(spice.common.enum.vote_type.VoteType['UPVOTE'], 'Upvote'), (spice.common.enum.vote_type.VoteType['DOWNVOTE'], 'Downvote')], max_length=250)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
