# Generated by Django 3.0.6 on 2020-05-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('modified_date', models.DateField()),
                ('created_date', models.DateField()),
                ('id', models.DecimalField(decimal_places=10, editable=False, max_digits=19, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('super_user', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
